# Generated by Django 2.2.3 on 2019-07-06 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190705_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('repo_name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=200)),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Repo')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_id', models.IntegerField()),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Event')),
            ],
        ),
    ]
